Homework1
made-ml-in-prod-2021/yurchenkopo pull request #2
Opened 2021-05-05 19:48 UTC by YurchenkoPO

Не буду скрывать, дз я делал по примеру преподавательского проекта (конечно чтобы научиться писать хороший код с правильной структурой), поэтому структура скорее всего будет знакома. Основной код находится в папке /ml_project/src, отчет генерируется в /ml_project/outputs вместе с логами.
В данном проекте я решал [задачу](https://www.kaggle.com/ronitf/heart-disease-uci) бинарной классификации, предложенную в блоге при помощи RandomForest и LogisticRegression. Основное отличие от преподавательского проекта в реализации достаточно гибкой структуры конфиг-файлов с библиотекой hydra, при помощи которой можно заменять отдельные смысловые куски параметров, оставляя неизменными остальные. Также добавил возможность изменения параметров модели прямо в конфиг-файле.
Основной, не самой различимой, проблемой задачи было понять, какие признаки являются численными, а какие категориальными (они все в датасете имеют тип int). Поэтому, чтобы корректно обработать категориальные фичи было принято решение добавить в категориальный пайплайн дополнительный FunctionTransformer, который приводил их к типу object. 
Был добавлен отдельный файл для получения предсказаний на основе тестовой выборки без меток классов и конфиг для него.
Для тестов реализовано генерирование данных на основе тренировочных в реалистичных диапазонах в файле conftest.py.

Считаю, что могу претендовать на 35 баллов (не стал реализовывать только CI - 12ый пункт дз)

2021-05-08 09:28 UTC, ol-ga-00 reviewed
Файл .gitkeep обычно помещают в пустую директорию, дабы сказать "директорию пустая, но она нам нужна; пусть гит знает о существовании этой директории"
Если в директории помимо .gitkeep есть и другие файлы, то .gitkeep теряет свою актуальность. Прошу удалить такие файлы, где они не актуальны.

2021-05-08 09:31 UTC, ol-ga-00 reviewed
Директория ml_project/.venv является виртуальным окружением, его коммитеть не нужно

2021-05-08 09:31 UTC, ol-ga-00 reviewed
В отношении тестов рекомендую изучить статью https://habr.com/ru/post/448786/
Обратить внимание следует на "Спецификация областей(Scope) Fixture"

2021-05-08 09:38 UTC, ol-ga-00 reviewed
> Считаю, что могу претендовать на 35 баллов (не стал реализовывать только CI - 12ый пункт дз)

Прошу уточнить, где реализован кастомный трансформер

Требовалось придумать и реализовать его самому
Пример,
https://towardsdatascience.com/pipelines-custom-transformers-in-scikit-learn-the-step-by-step-guide-with-python-code-4a7d9b068156

2021-05-08 09:38 UTC, ol-ga-00 commented on ml_project/src/predict.py
> +def train_pipeline(predict_pipeline_params: DictConfig):
Думаю, что функцию логичнее назвать predict_pipeline
Вы согласны?

2021-05-08 19:58 UTC, YurchenkoPO commented
Да, за трансформер можно снимать баллы, я не знал, что конкретно имелось в виду. А вместо ноутбука, как я понял по заданию, достаточно иметь .py файл с отчетом. 
Все остальные замечания исправил.

2021-05-09 07:50 UTC, ol-ga-00 requested changes
> Да, за трансформер можно снимать баллы, я не знал, что конкретно имелось в виду. 

У вас ещё есть время его написать. Будете писать?

> А вместо ноутбука, как я понял по заданию, достаточно иметь .py файл с отчетом.

Да, вы правы!

> Все остальные замечания исправил.

1. В pr всё ещё вижу директорию ml_project/.venv, прошу её удалить. Пока она есть, апрув не поставлю, либо же объясните мне, почему её следует оставить
2. Не исправлена проверка ```assert model.predict(features).shape[0] == target.shape[0]```. Но это не критичное замечание, и без его исправления я готова поставить апрув. Только прошу сообщить, будете его исправлять или нет (ждать ли мне)

2021-05-09 07:50 UTC, ol-ga-00 commented on ml_project/tests/models/test_train_model.py
> +    assert model.predict(features).shape[0] == target.shape[0]
Думаю, что этот assert бессмысленный!
Функция predict у RandomForestClassifier всегда вернёт элемент, первая размерность которого будет совпадать с первой размерностью features
А размерности features и target совпадают, иначе бы функция train_model упала на моменте fit

Дополнительно (по желанию) рекомендую в тест модели попробовать добавить проверки, подобные этой https://scikit-learn.org/stable/modules/generated/sklearn.utils.validation.check_is_fitted.html

2021-05-09 19:09 UTC, YurchenkoPO commented
Удалил окружение, тесты убирать не стал, но ошибку понял. Дописывать трансформер уже не буду.
А преподаватели закрепляются за студентами в роли ревьюверов для будущих дз? То есть для второго дз, например, снова выбирать группу teachers или сразу Вас?

2021-05-10 09:54 UTC, ol-ga-00 commented
> А преподаватели закрепляются за студентами в роли ревьюверов для будущих дз? То есть для второго дз, например, снова выбирать группу teachers или сразу Вас?

Не закрепляются, выбирайте группу teachers

2021-05-10 09:55 UTC, ol-ga-00 approved these changes
За задание ставлю 32 балла

2021-05-10 09:59 UTC, merged